### ISSUE TITLE
Where is a fontforge website translation?

### ISSUE THREAD

**Issue by sebuls** [fontforge/fontforge.github.io#101]
When I click website translation in
https://fontforge.github.io/en-US/documentation/customizing/uitranslationnotes/
I get the message 404 not found.

**Comment by jrbastien** [comment]
This works well for me.  Do you still have the problem?

**Comment by JohnWong** [comment]
This works for me either.

**Comment by anktkr** [comment]
@jrbastien  I think this and #100  are a result of a misunderstanding where people expect translated webpages instead of being asked to translate. How can this be closed ?

**Comment by jrbastien** [comment]
There is currently no translation available in non-English language for fontforge.github.io.  Should a user wish to have one in his own language, he is welcomed to contribute as per the instructions provided on the page  [https://fontforge.github.io/en-US/site/](https://fontforge.github.io/en-US/site/), section Translations.

I think this answers the question, therefore I'm closing this issue.
