### ISSUE TITLE
Unwanted layer switching when switching between characters in glyph view

### ISSUE THREAD

**Issue by hyvyys** [fontforge/fontforge.github.io#106]
As described in the topic, this behaviour makes it really tedious to copy things between characters, especially in a multi layered font. Issue becomes especially visible when additional foreground layers are created and utilized.
Is there any way to improve this?
Additionally there is an error when trying to copy content, switch character, then switch layer (back to the originally selected) and paste content: "Sorry this file is too complex for me" which is annoying too, and the work around is pasting in the newly selected layer then cutting and pasting again into the originally selected layer.
These were encountered on Windows 10, FF version 7 April 2016

**Comment by jtanx** [comment]
This issue tracker is for the website - please post your issue here https://github.com/fontforge/fontforge/issues

**Comment by hyvyys** [comment]
Oh, sorry. I did. How do I delete this instance now? Or can you do it?

**Comment by jtanx** [comment]
No big deal - you can simply close this issue and then repost on that other issue tracker.
