### ISSUE TITLE
Top-level minutia

### ISSUE THREAD

**Issue by skef** [fontforge/fontforge.github.io#126]
At some point about five years ago someone half-constructed a website for FontForge including a version of the repository docs rearranged into a sort of pile here: http://fontforge.github.io/en-US/documentation/ and including an almost unusable version of the Python interface doc: http://fontforge.github.io/en-US/documentation/scripting/python/ . These pages have largely been left alone since. (One or two change sets have been ported into them, probably by whoever implemented the changes.) 

As a result the best current documentation of aspects of the program not mentioned in [Design with FontForge](http://designwithfontforge.com/en-US/index.html) comes from pointing one's browser to a copy of the repo docs, which actually still works OK. Accordingly, the project administrators should have backed out to a slightly modified version of those docs about 4.5 years ago instead of leaving the glaring regression in place. That could still happen now, but the passive-aggressive silence on that option in fontforge/fontforge#3530 suggests it isn't on the table. 

Instead, interested parties are invited to overhaul the website with some other technology. I really don't want to spend my time on this, but I also don't want the time I spent improving the python interface to come to nothing because no one can find the documentation for it. And apparently isn't either/or. 

So this is the first of likely a number of issues in which I ask about aspects of the documentation while trying to reorganize things while kind of pissed off. This one is about the top-level stuff not related to the repo documents. 

1. @davelab6 has mentioned in a number of contexts that he no longer supports FontForge work. Will Tug Libre money still reach FontForge somehow? Does anyone check FreedomSponsors? Or should this stuff just devolve into a Paypal link, maybe included in the common header?

2. Can the registration process go away, given that a) the vast majority of users don't get the software by this route anyway, and b) it's there to encourage people to register for fontforge-announce, a list that [no one thought to notify about the March 17th release](https://sourceforge.net/p/fontforge/mailman/fontforge-announce/)? (Same with the twitter and facebook accounts.)

**Comment by frank-trampe** [comment]
@skef, the release announcement, which I have mostly written, has not gone out because the Ubuntu builds didn't work. I am planning to fix that in the next few days. With all the changes happening, we might even rerelease on all platforms. The announcement list is an important part of the project strategy. There are not a lot of type designers in the world, so maintaining a viable ecosystem for FontForge requires a higher level of engagement than would suffice for something of more general interest like the GIMP.

As for TUG, it is still capable of passing along any money marked for FontForge, with the additional benefit of tax-deductibility for the donor, I think. We've incorporated a FontForge Foundation, but it's not yet 501(c)3 material.

**Comment by frank-trampe** [comment]
Sorry for my silence on #3530. There seemed to be enough qualified people working on it to reach a reasonable conclusion. I'll post there shortly.

**Comment by skef** [comment]
In fairness to my crabbiness, the 2017 release doesn't seem to have been mentioned either ...

**Comment by skef** [comment]
For Tug, the page here: https://www.tug.org/fonts/librefontfund.html *mentions* FontForge, and the donation page here *mentions* the possibility of directing donations via a comment, but that system seems pretty dodgy for this project's purposes. If this is an important route it would be better if they could add sub-bullets under Libre for specific projects.

**Comment by frank-trampe** [comment]
Regarding TUG, I'll talk to Dave about making earmarks easier. It does seem unlikely to serve its stated purpose presently, and we have gotten no money through TUG in years, but having a 501(c)3 option seems worth some trouble.

**Comment by frank-trampe** [comment]
I did announce the 2017 release on the mailing list. I still have the e-mail.

**Comment by skef** [comment]
> I did announce the 2017 release on the mailing list. I still have the e-mail.

OK -- I have no reason to think otherwise besides the archive, and I can imagine the archive being inaccurate. (Or is that even the right page anymore?)

**Comment by frank-trampe** [comment]
Hmm. It's definitely not in the SourceForge archive. Can somebody who was subscribed on July 31st of 2017 check for an e-mail from me that day? It may not have gone through.

**Comment by skef** [comment]
The current plan, worked out in the other issue, is to archive the Kramdown files and focus on the HTML. I'll do some cleanup on the docs in the repo and restyle them to match the website. I'll probably also add a touch of javascript to get a navigation header on all the pages instead of just `overview.html`, but nothing very fancy and no js library dependencies.

I'll probably replace the tables in the python page and the free-form markup on the scripting pages with classed DIVs. That will allow methods and such to be styled in CSS, so a method will look distinctive but not be stuck in the table grid.

**Comment by davelab6** [comment]
@skef happy to chat about tug lff. I'm in NYC and fairly free Tuesday and Wednesday afternoon this week.

**Comment by davelab6** [comment]
Also happy to try to figure out a time when @jtanx and anyone else (@pathumego?) who might be interested can join

**Comment by frank-trampe** [comment]
@davelab6, the main issue, to my knowledge, is whether we can make is easier for somebody who clicks through from the FontForge site to the TUG site to donate earmarked money. Obviously, FontForge can't be the driving concern in the design of the TUG site, but there might be a lot of other projects that would benefit from having an easy workflow for earmarked donations.

**Comment by skef** [comment]
Yes, that's the only TUG-specific, website-related issue. Everything seems to be good at the organization level, but it's not very clear at the website design level how to donate to the Libre fund for specific projects. Even just a purely textual note on specifically how to use the comment field to earmark (e.g. "Type 'FontForge' in the comment field to ...") would be a substantial improvement.

**Comment by davelab6** [comment]
The download flow now has a direct PayPal link. My guess is the LFF link on the funding page can be replaced entirely by that?

It's a pity the "edit this page" link has gone

**Comment by davelab6** [comment]
> Will Tug Libre money still reach FontForge somehow? 

I'm not aware of a specific need that the fontforge community has that can be met with the modest balance available.

> Does anyone check FreedomSponsors?

I remember I added their bot to fontforge GitHub issues, but I don't think they ever raised any funds. 

> Or should this stuff just devolve into a Paypal link, maybe included in the common header?

Sgtm

**Comment by frank-trampe** [comment]
@davelab6, I'm not arguing for a grant from the TUG general fund. The purpose that TUG would serve, even with FontForge set up to accept PayPal donations directly, is accepting contributions on behalf of FontForge from donors who want tax deductions, in which case the contributions would be referred from FontForge and earmarked for FontForge. There's just not a particularly elegant way to do that right now.

**Comment by jtanx** [comment]
Just saying, but I have no idea where the money from the current paypal links on the website goes to, or whose paypal that even is, and how it's spent.

**Comment by skef** [comment]
I sent three bucks, so we'll see what happens if anything.

**Comment by frank-trampe** [comment]
@skef, @jtanx, there is a PayPal account for funding@fontforge.org that I manage. The money sits there until we need it. In the past, I would save money to fund various projects. In general, other contributors have declined money, so I've been the biggest vendor to the project. But then the Libre Graphics Meeting stopped reimbursing travel, so the most of the FontForge budget for at least the last three years has gone towards that end. This year's expenses are paid, and we currently have about $400. I think that I calculated once that we get about $0.02 in donations per FontForge download. It's a good thing that we don't pay for bandwidth.
