### ISSUE TITLE
FontForge Twitter account should be more active

### ISSUE THREAD

**Issue by ctrlcctrlv** [fontforge/fontforge.github.io#133]
The @FontForge Twitter account has not tweeted in two years. I tweet a lot of stuff to it, most recently https://twitter.com/HW_BEAT_THAT/status/1151738900907319298, but it never replies and never shows what we are doing as a community to improve FontForge. It doesn't talk about our new features and our new bug fixes; many in the community *wrongly* believe FontForge to be stagnant, I believe in part due to this, most recently @eliheuer, who is awesome by the way, this is not a criticism of him, gave a talk in NYC where he basically said FontForge is a stagnant "art project" by George none of us can figure out how improve or even work with, briskly moving on to other tools.

I volunteer to take it over. If you don't like me for whatever reason, please choose someone to take it over. I will keep the tweets strictly about FontForge and our work, no memes or political stuff, that's my promise if I'm chosen. I plan to mostly tweet every time a new PR is merged, showcasing what we've accomplished recently. 

CC: @frank-trampe @skef @davelab6 @jtanx @khaledhosny

**Comment by jtanx** [comment]
I personally don't mind, but having said that I have no involvement with any of the social media outlets that FontForge has.

**Comment by frank-trampe** [comment]
We do indeed need to get the Twitter account going, and we finally have somebody to do it. I've pinged @davelab6 about getting a TweetDeck set up.

**Comment by StephenLynx** [comment]
Only trash people care about twitter.

**Comment by frank-trampe** [comment]
@StephenLynx, the issue tracker is not an appropriate place to start a flame war. I would suggest using a medium that caters to "trash people" for said pursuit.

**Comment by davelab6** [comment]
I'll email you and Frank the login.

I blocked him. Bye Felicia.

**Comment by frank-trampe** [comment]
@davelab6, thanks for setting that up.

@ctrlcctrlv, you ought to have access via TweetDeck now.

**Comment by ctrlcctrlv** [comment]
Yup, thanks! This is solved.
