### ISSUE TITLE
Funding page is a 404

### ISSUE THREAD

**Issue by skef** [fontforge/fontforge.github.io#156]

**Comment by ndiesslin** [comment]
Should this funding link go to /en-US/donate/ instead of /en-US/funding/?

**Comment by frank-trampe** [comment]
Where is the link in question?

**Comment by ndiesslin** [comment]
I noticed it in the footer: 
<img width="1014" alt="Screen Shot 2021-05-06 at 3 55 48 PM" src="https://user-images.githubusercontent.com/2882707/117364526-9fcea180-ae83-11eb-9a92-745d84bf86f8.png">

**Comment by frank-trampe** [comment]
Oh. I think we can just take that out since there's already a donate page. I'm not sure what happened to the original funding page, but it would probably be out of date anyway.

**Comment by ndiesslin** [comment]
Thank you for adding guidance on this link Frank!

**Comment by frank-trampe** [comment]
And thanks for fixing it.
