### ISSUE TITLE
Update downloads count on hompage, show it on downlaods page too

### ISSUE THREAD

**Issue by davelab6** [fontforge/fontforge.github.io#16]
On homepage
- [x] Use https://help.github.com/articles/getting-the-download-count-for-your-releases/ to show how many times the latest release has been downloaded across (sum of all platforms) on the existing "4,059 downloads this week" string

On each platform download page, 
- [ ] show the total and individual count, and use d3.js to show a pie chart of each in proportion
- [x] ~~~show the download filesize with http://bernii.github.io/gauge.js/~~~ (cancelled as more design thinking required)

**Comment by davelab6** [comment]
http://www.somsubhra.com/github-release-stats/ can be used to check the correct count numbers. 

@vitalyvolkov please look into this :)

**Comment by davelab6** [comment]
Thanks @vitalyvolkov this is looking good :)

I wonder if you could confirm that the 2nd count is really 'this month' as labelled in https://github.com/fontforge/fontforge.github.io/blob/master/_layouts/homepage.html#L40 - I can't figure out from the js code what it is doing =)

**Comment by davelab6** [comment]
@vitalyvolkov when I look at https://api.github.com/repos/fontforge/fontforge/releases/latest I see the download count around ~1,200 total... and the homepage shows this too!! :dancer: 

Buuuuut, the windows page's chart looks weird

![screen shot 2015-05-03 at 10 41 22 pm](https://cloud.githubusercontent.com/assets/261579/7448355/93cb6d8e-f1e5-11e4-8b51-9a5d9d118d92.png)

**Comment by davelab6** [comment]
The graph is still not right:

![screen shot 2015-05-07 at 12 48 10 am](https://cloud.githubusercontent.com/assets/261579/7506058/c0f3bc52-f452-11e4-8f3c-c008e393e180.png)

I checked https://api.github.com/repos/fontforge/fontforge/releases/latest and the numbers are right, and that is 87% for windows, but the graph doesn't look like that at all.

**Comment by andreaslarsen** [comment]
Closing this as the count on the homepage works fine and the platform specific ones went poof in todays style update
