### ISSUE TITLE
Bintray storage disabled — switch to other storage for CI artifacts

### ISSUE THREAD

**Issue by Symbian9** [fontforge/fontforge.github.io#162]
Bintray actually disabled its storage access and will be shutdown:

- https://bintray.com
> Thanks for supporting Bintray! This service has now been sunset, and to assist with migration to the JFrog Platform, paid accounts can login until July 4th. 

As a result FontForge artifacts NOT available anymore:

- ~~https://dl.bintray.com/fontforge/fontforge/~~

### REFERENCE

- https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md#accessing-ci-build-archives

**Comment by Symbian9** [comment]
> You can grab the latest from the artifacts on e.g.

@jtanx @ctrlcctrlv, GitHub Artifacts are NOT available for download for not logged-in users / non-GitHub users.

Please, upload latest artifacts using @probonopd's `uploadtool` as `continuous` pre-release assets:

- https://github.com/probonopd/uploadtool

**Comment by ctrlcctrlv** [comment]
@Symbian9 You can make an issue for that over on FontForge tracker. I don't know that we're gonna do it, but if you put a PR there it could happen after some discussion.

**Comment by probonopd** [comment]
Also check out https://github.com/tcnksm/ghr. Simple, does the job.

**Comment by ctrlcctrlv** [comment]
That'd pollute the Releases page with in-development stuff…

**Comment by Symbian9** [comment]
> That'd pollute the Releases page with in-development stuff…

No, as at the same time only single latest build would available as assets (no need to store all previous nightly builds)

**Comment by ctrlcctrlv** [comment]
Still, wouldn't this mean that users are shown a development build before a stable build on the Releases page? That's what I mean by pollute, not that I thought it'd flood the Releases page.

In FontForge speak, a release is always a stable release. These are just developer builds.

**Comment by Symbian9** [comment]
> Still, wouldn't this mean that users are shown a development build before a stable build on the Releases page?

Users should read what they are grabbing:

- stable releases tagged as `release`;
- unstable releases tagged as `pre-release`;
- also we may add custom tag for `pre-release` — ***I propose add*** `nightly` ***tag and upload latest builds as assets to it.***

For the *latest* `release` there is already a link:

- https://github.com/fontforge/fontforge/releases/latest
