### ISSUE TITLE
Correct derisive language against certain platforms

### ISSUE THREAD

**Issue by ultrasquid** [fontforge/fontforge.github.io#17]
http://fontforge.github.io/en-US/downloads/mac/ makes mention of using a "real" mouse on a Mac. Macs have not shipped with a one-button mouse since 2005, when Apple began including the Mighty Mouse, . The current standard equipment for desktop Macs is the Magic Mouse which has a multi-touch surface, and laptops have a multitouch trackpad. Even so, a one button mouse is no less real than a two or three button mouse, or a two button with clickable scroll wheel effective three button mouse currently common on the market.

There was a reference elsewhere in the old documentation on fontforge.sf.net (which doesn't seem to currently be online) to Macintoy. There are no insults to other systems like Windoze or Eunuchs. If that page does turn up again, let's be sure to treat everyone  equally.

I guess the point I'm making is that configuration instructions should be geared  toward helping people deal with the equipment they have without implying that it or they themselves are inferior, which seems to be the implication in the original text.

**Comment by pathumego** [comment]
seems like someone fixed it :)
