### ISSUE TITLE
fontforge fails to build in Homebrew

### ISSUE THREAD

**Issue by mkporwit** [fontforge/fontforge.github.io#37]
I get the following when I try to build the latest fontforge through homebrew:
mkporwit-macmini[~]$ brew doctor
Your system is ready to brew.
mkporwit-macmini[~]$ brew upgrade python gettext libpng jpeg libtiff giflib cairo pango libspiro czmq fontconfig automake libtool pkg-config glib pango
Error: python-2.7.8_2 already installed
Error: gettext-0.19.3_1 already installed
Error: libpng-1.6.14 already installed
Error: jpeg-8d already installed
Error: libtiff-4.0.3 already installed
Error: giflib-4.1.6 already installed
Error: cairo-1.14.0 already installed
Error: pango-1.36.8 already installed
Error: libspiro-20071029 already installed
Error: czmq-2.2.0_1 already installed
Error: fontconfig-2.11.1 already installed
Error: automake-1.14.1 already installed
Error: libtool-2.4.2 already installed
Error: pkg-config-0.28 already installed
Error: glib-2.42.1 already installed
mkporwit-macmini[~]$ brew upgrade fontforge
==> Upgrading 1 outdated package, with result:
fontforge 20141014
==> Upgrading fontforge
Warning: Building source; cellar of fontforge's bottle is /usr/local/Cellar
==> Downloading https://github.com/fontforge/fontforge/releases/download/20141014/fontforge-20141014.tar.gz
Already downloaded: /Library/Caches/Homebrew/fontforge-20141014.tar.gz
==> Downloading https://github.com/fontforge/fontforge/commit/bce235d23b8.diff
Already downloaded: /Library/Caches/Homebrew/fontforge--patch-8ec20f07bbf5f93c052bed7304c6e667046910ef.diff
==> Patching
patching file osx/FontForge.app/Contents/MacOS/FontForge
==> ./bootstrap

bootstrap:   error: One of these is required:
bootstrap:                 libtoolize glibtoolize
bootstrap: running: --quiet
./bootstrap: line 4287: --quiet: command not found

mkporwit-macmini[~]$ which glibtoolize
/usr/local/bin/glibtoolize

mkporwit-macmini[fontforge]$ more 01.bootstrap 
2014-11-21 18:33:44 -0800

./bootstrap

bootstrap:   error: One of these is required:
bootstrap:                 libtoolize glibtoolize
bootstrap: running: --quiet
./bootstrap: line 4287: --quiet: command not found

HOMEBREW_VERSION: 0.9.5
HEAD: 78f4e848ffcd77634b6f446bb7e3f764ebd95a76
HOMEBREW_CELLAR: /Users/mkporwit/Developer/homebrew/Cellar
CPU: 8-core 64-bit ivybridge
OS X: 10.10.1-x86_64
Xcode: 6.1
CLT: 6.1.0.0.1.1413057044
X11: 2.7.7 => /opt/X11
mkporwit-macmini[fontforge]$ 

This has been going on for a while now.

**Comment by pathumego** [comment]
Fixed in elsewhere
