### ISSUE TITLE
Move all them root folder png's

### ISSUE THREAD

**Issue by larsenwork** [fontforge/fontforge.github.io#58]
It's messy :) 

Can't they be moved to a folder?

**Comment by andreaslarsen** [comment]
@davelab6 I can see a lot of it stems from this: https://github.com/fontforge/fontforge.github.io/commit/466ffd54bb6ae53058429701f6c53814b52405fb :)

**Comment by andreaslarsen** [comment]
@davelab6 I created an archive branch with all the files and then moved html, css + image files to an old folder. 

https://github.com/fontforge/fontforge.github.io/pull/62

**Comment by davelab6** [comment]
I don' think the HTML should 404. Moving the CSS and images could be okay, but, I don't really see the sense in this. I think the old content should be migrated and the old information removed and the html replaced with a redirect, either automatic to the new page that holds all the equivalent but up to date info, or with a set of links pointing to where the new info is :)

**Comment by andreaslarsen** [comment]
The html isn't 404 - it's just in the /old folder instead

**Comment by andreaslarsen** [comment]
So users + google can still find it on e.g. fontforge.github.io/old/someOldPage.html

**Comment by andreaslarsen** [comment]
I use e.g. Brackets for code editing and it's a pain to have to scroll through so many files when working in the fontforge.github.io folder :smile:

**Comment by davelab6** [comment]
> The html isn't 404 - it's just in the /old folder instead

I don't understand. That means the original location will 404:

![screen shot 2015-05-09 at 7 21 45 pm](https://cloud.githubusercontent.com/assets/261579/7551456/acbfabb2-f680-11e4-8dee-864e4b2b0fff.png)

**Comment by davelab6** [comment]
> I use e.g. Brackets for code editing and it's a pain to have to scroll through so many files when working in the fontforge.github.io folder

Just open the en-us folder :)

**Comment by andreaslarsen** [comment]
no - it will just be fontforge.github.io/old/python.html ?

**Comment by andreaslarsen** [comment]
en-us is not enough when fiddling with stylesheets, screenshots and other assets
a root folder should always be as "clean" as possible :)

**Comment by andreaslarsen** [comment]
hmm...I just assumed the links had relative paths :/

**Comment by andreaslarsen** [comment]
just looked at a couple of the html files and they all used relative paths so all those links will work also in a /old folder - which other links are you referring to?

**Comment by davelab6** [comment]
Off site links.

**Comment by andreaslarsen** [comment]
For those I actually think a 404 page would be better. To let people know about the new website (so they now where the most up to date information is) and tell them that they still can browse the old site on fontforge.github.io/old

I know there's a lot of information on the old website that isn't on the new one (yet) but the old website also contains a lot of outdated information.

**Comment by davelab6** [comment]
Okay I think this can work - with some JS you can make a single 404 page -
https://help.github.com/articles/custom-404-pages/ - that redirects the
user to the /old/$currentPage based on the URL. And thus keep everything
tidy without breaking incoming links too badly :)

**Comment by andreaslarsen** [comment]
I'm not sure that would work. Take a current incoming link that would 404 e.g. http://fontforge.github.io/en-US/andreas

Redirecting me to http://fontforge.github.io//old/en-US/andreas will still not work and just confuse "me"

Maybe if we just told people on the 404 page that they might be able to find `$currentPage`on `/old/$currentPage` ?

**Comment by davelab6** [comment]
Just whitelist it, then it will work when it works and not work when it doesnt work? :)

**Comment by andreaslarsen** [comment]
ok, I have only really used .htaccess for redirects to someone can probably cook a javascript solution faster than me

**Comment by larsenwork** [comment]
#81 closes this (moves the images but not the html pages so no issues with incoming links)
