### ISSUE TITLE
Remove the download counts from the webpage

### ISSUE THREAD

**Issue by andreaslarsen** [fontforge/fontforge.github.io#59]
At least from the download pages. It's uninteresting information for users wanting to download, it distracts from the main purpose (to get users to download) and if we want to tell a story then this is much more relevant: https://github.com/fontforge/designwithfontforge.com/issues/94

**Comment by adrientetar** [comment]
Yeah.

**Comment by andreaslarsen** [comment]
One of many things I've done here: https://github.com/fontforge/fontforge.github.io/pull/61

**Comment by andreaslarsen** [comment]
They are now removed :)
