### ISSUE TITLE
Detach this fork from summerstyle

### ISSUE THREAD

**Issue by andreaslarsen** [fontforge/fontforge.github.io#65]
Can be done by contacting support - see last sentence:
https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/#footer

**Comment by davelab6** [comment]
Go ahead, you are in the owners team :) https://github.com/orgs/fontforge/teams/owners

**Comment by andreaslarsen** [comment]
yep, just wanted to ask before doing it

**Comment by andreaslarsen** [comment]
Got reply from github staff. Sounds like it's extracting we want?

Would you like the repo to be detached or extracted? Detaching un-forks only your repo, while extracting moves your fork and its children into a new network.

**Comment by davelab6** [comment]
detatch I think

https://github.com/summerstyle/fontforge.github.com/network 

https://github.com/fontforge/fontforge.github.io/network

**Comment by andreaslarsen** [comment]
ok, not that many childrens anyway.
