### ISSUE TITLE
New hero screenshot

### ISSUE THREAD

**Issue by davelab6** [fontforge/fontforge.github.io#70]
@andreaslarsen could you make a replacement for the homepage masthead screenshot that uses your latest theme? :)

![](https://raw.githubusercontent.com/fontforge/fontforge.github.io/master/assets/img/home-hero-screenshot.png)

File is here: https://github.com/fontforge/fontforge.github.io/blob/master/assets/img/home-hero-screenshot.png

**Comment by andreaslarsen** [comment]
sure

**Comment by andreaslarsen** [comment]
part of lighten up pr
