### ISSUE TITLE
Add Twitter link

### ISSUE THREAD

**Issue by pathumego** [fontforge/fontforge.github.io#73]
Add twitter link to footer?

**Comment by andreaslarsen** [comment]
yeah, why not :)

**Comment by andreaslarsen** [comment]
Go big or go home...
![fontforge open source font editor 20150526](https://cloud.githubusercontent.com/assets/3859425/7822297/e299db82-03f4-11e5-83f2-cc3cad0921ba.png)

**Comment by pathumego** [comment]
Nice.. added in #66  Closing here
