### ISSUE TITLE
unified download page and direct download from frontpage

### ISSUE THREAD

**Issue by larsenwork** [fontforge/fontforge.github.io#75]
*Direct download*
@adrientetar mentioned this earlier and I think it's a viable thing to do it now with the mac installer making it a lot easier to get started

*Unified download page*
I think the all the download information can be on one page since the pages are so short anyway (the mac page will be trimmed a lot after new installer).

**Comment by pathumego** [comment]
+1 With show/hide toggles if there is more stuff

**Comment by andreaslarsen** [comment]
@pathumego Yep, like how I did it on the mac download page right?

**Comment by andreaslarsen** [comment]
and to continue this track of flattening the structure a bit then trying to have only >2 subdir in the documentation dir...no more about/faq where about is a blank page and kill the subnavn (too much with navigation 4 places (topnavn, subnav, breadcrumbs and footer) - 3 should be more than enough

**Comment by andreaslarsen** [comment]
https://github.com/fontforge/fontforge.github.io/tree/flat-structure

**Comment by larsenwork** [comment]
#85 closes this, discuss there
