### ISSUE TITLE
Tagline and Short description

### ISSUE THREAD

**Issue by pathumego** [fontforge/fontforge.github.io#76]
#72 And generally website, twitter and others will need a sample line that explains what FF is and a small  50 Word descriptor.

**Comment by pathumego** [comment]
Twitter says - `a font editor`
GH Org page says - `Free (libre) font editor for Windows, Mac OS X and GNU+Linux`
Current Website says - `Create and edit fonts in many formats: OpenType, TrueType, AAT, PostScript, Multiple Master, CID-Keyed, SVG and various bitmap formats`

**Comment by andreaslarsen** [comment]
yep, all site wide social data should be added as variables in the root yml and then added to the header html in _includes

**Comment by pathumego** [comment]
Ok so we got to say,

- The libre nature (Libre, Freedom, Free)
- Cross platform (Anyone, Everybody, Whole world, world, platforms, Cross platform,)
- Free (Free , -do- )

And just thinking out loud,

- A Font Editor, with Freedom
- A Libre Font Editor
- Font Editor for the whole world
 
- The Free Font Editor for Windows, Mac, and GNU/Linux
- A Font Editor, for free, with freedom
- The Free (Libre) Font Editor
- Freedom to edit fonts.. :facepunch: 
- A free font editor, for the whole world :santa: 


And the descriptor could be something that mentions all or few of these,

- formats
- documented 
- community developed
- Fast releases
- You can make it better
- Advanced

**Comment by JoesCat** [comment]
Pathum Egodawatta wrote:
> - The Free Font Editor for Windows, Mac, and GNU/Linux

FontForge - A Free Font Editor that works on Windows, Mac, GNU/Linux, BSD, 
and other operating systems.

(I think... name it, describe it, acknowledge where it runs (including 
lesser-known platforms, eg Fedora is promoting ARM, others are trying big 
iron like AIX, etc...))

**Comment by andreaslarsen** [comment]
I don't think niche information doesn't belongs in a tagline so either "Win, Mac and Unix" or just "cross platform".

**Comment by pathumego** [comment]
Agree with @andreaslarsen

 @JoesCat I think that info could be a part of Description and/or the new downloads page #75

**Comment by larsenwork** [comment]
https://github.com/fontforge/fontforge.github.io/blob/2a02ca92f1078c46eee8736b1df547f03fbdc4a2/_includes/html-start.html

**Comment by pathumego** [comment]
@larsenwork :+1:  nice, lets close this soon...

`A Free/Libre Font Editor, that works on many operating systems`

`A Cross platform Font Editor, with Freedom` is my favourite. I think the word freedom would both indicate the free and opensource nature and wont have the confusion that @larsenwork mentioned elsewhere. And I think it is important to indicate the Freedom. As I mentioned earlier the main pointers we should focus is,

- Font Editor
- Libre
- Crossplatform
- Free (Price) 

So one of the top coupled with the description in the bottom would do the job. (Please feel free to edit, Im only talking about the contents, here)

`FontForge is a Free and Open Source font editor that works on Windows, Mac,  GNU/Linux and many other Unix systems. With FontForge you can create and edit fonts in many formats: OpenType, TrueType, UFO,AAT, PostScript, Multiple Master, CID-Keyed, SVG and various bitmap formats. And you can join the community of type lovers to build FontForge together.`

**Comment by larsenwork** [comment]
The description should be <150 characters :)

**Comment by larsenwork** [comment]
And not just because I like things short (I do) but because it's the max length for one of them (the other is <200) so it's easier to use same description and keep it <150

**Comment by pathumego** [comment]
Ha ha, I like them shorter too. I wasn't thinking about length at all. We
can shorten it further. I'll get my copywriter friend :)
