### ISSUE TITLE
lighten up round two...

### ISSUE THREAD

**Issue by larsenwork** [fontforge/fontforge.github.io#79]
sorry guys, just had an idea I had to try real quick. I visited the website on a big display earlier and got annoyed by the dominant horizontal lines so got rid of a couple of them.

![fontforge open source font editor 20150529](https://cloud.githubusercontent.com/assets/3859425/7872684/3941afa4-059a-11e5-8345-dc7adeb8412d.png)
![documentation 20150529](https://cloud.githubusercontent.com/assets/3859425/7872685/3ac2caa2-059a-11e5-9020-4a0d4e9eee8a.png)

**Comment by larsenwork** [comment]
ping @pathumego and @davelab6

**Comment by davelab6** [comment]
I know what you mean... I think the 4 top nav links could be white or with a lighter background to set them out from the masthead overall.

**Comment by pathumego** [comment]
Agree with @davelab6 White links would be nice.

**Comment by JoesCat** [comment]
A popular color set in the days of 16 color graphics was yellow text on 
blue.

Light text on dark backgrounds are a nice change of pace, but I noted that 
you may want to avoid the light/white colors for text, as they come out 
very washed-out for anyone printing web pages to a printer.

**Comment by larsenwork** [comment]
@davelab6 done
@JoesCat that's what `media print` is for - I made it so all the text is black + backgrounds white

![install fontforge on mac os x 20150529](https://cloud.githubusercontent.com/assets/3859425/7878237/1b6866ee-05e5-11e5-9a22-ac09447858ca.png)
![fontforge open source font editor 20150529](https://cloud.githubusercontent.com/assets/3859425/7878238/1b899008-05e5-11e5-9e63-fed883eac1e9.png)

**Comment by jtanx** [comment]
Looks good otherwise, but IMO, those hyperlinks now look like the 'spell checker' incorrect spelling underline.

**Comment by larsenwork** [comment]
@jtanx I'm also unsure about that - I like it (and did it) because it's a visual continuation of the orange line in the logo...

**Comment by larsenwork** [comment]
nb: the anti alias hack doesn't work in paparazzi so the text looks bolder in screenshots

**Comment by larsenwork** [comment]
@jtanx looks even less like spell check if we make it a little bit thicker
![screen shot 2015-05-29 at 09 40 37](https://cloud.githubusercontent.com/assets/3859425/7878441/e1e8dd0c-05e6-11e5-9a60-77b5c10b68fa.png)

**Comment by pathumego** [comment]
@jtanx  :+1:

**Comment by larsenwork** [comment]
@pathumego see #82

**Comment by davelab6** [comment]
I think the links color change fading on mouse over needs work, its a bit
jarring at the moment

**Comment by larsenwork** [comment]
ye

**Comment by pathumego** [comment]
What link, the top links?

**Comment by davelab6** [comment]
The fade in all cases I saw was kind of jumping at the start

On Saturday, 30 May 2015, Pathum Egodawatta <notifications@github.com>
wrote:

> What link, the top links?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fontforge/fontforge.github.io/issues/79#issuecomment-106986442>
> .
>


-- 
Cheers
Dave

**Comment by larsenwork** [comment]
fixed, were no fade before
