### ISSUE TITLE
History link on template is incorrect

### ISSUE THREAD

**Issue by Nzen** [fontforge/fontforge.github.io#88]
### Saw:
http://fontforge.github.io/en-US/history/ link in lower left footer of most pages. Clicking the link gives 404

### Expected:
http://fontforge.github.io/en-US/project/history/

### Likely:
fontforge.github.io/_includes/footer.html needs the updated link

**Comment by larsenwork** [comment]
Thanks, fixed - although the page itself is empty so I also commented the link out of the footer until @davelab6 or some other "old" guy writes the page :smile:
