### ISSUE TITLE
Mac download link is broken

### ISSUE THREAD

**Issue by eabay** [fontforge/fontforge.github.io#98]
I tried to download Mac version from website but the link from `Short Guide` is broken and the link from `Detailed Guide` points to an older version.

This also affects the [installation](https://github.com/caskroom/homebrew-cask/blob/master/Casks/fontforge.rb) with homebrew because it points to the broken link too.

Removing the phrase `Terminal_only` from [releases page](https://github.com/fontforge/fontforge/releases) can fix the problem. I suppose there is a reason for that phrase but the note above explains everything.

**Comment by elisazernik** [comment]
I noticed this too. Am not sure who to contact about it.

**Comment by ultrasquid** [comment]
Until that's fixed, please try:
http://fuuko.libferris.com/osx/packages/201509/
It's a little outdated, but it works.

On Fri, Feb 5, 2016 at 7:10 AM, elisazernik <notifications@github.com>
wrote:

> I noticed this too. Am not sure who to contact about it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fontforge/fontforge.github.io/issues/98#issuecomment-180394409>
> .
>



-- 
-- 
Jason Pagura
zimbach at gmail dot com

**Comment by ultrasquid** [comment]
The latest official releases are at:
https://github.com/fontforge/fontforge/releases

On Fri, Feb 5, 2016 at 10:16 AM, Jason Pagura <zimbach@gmail.com> wrote:

> Until that's fixed, please try:
> http://fuuko.libferris.com/osx/packages/201509/
> It's a little outdated, but it works.
>
> On Fri, Feb 5, 2016 at 7:10 AM, elisazernik <notifications@github.com>
> wrote:
>
>> I noticed this too. Am not sure who to contact about it.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/fontforge/fontforge.github.io/issues/98#issuecomment-180394409>
>> .
>>
>
>
>
> --
> --
> Jason Pagura
> zimbach at gmail dot com
>



-- 
-- 
Jason Pagura
zimbach at gmail dot com

**Comment by Astrovic** [comment]
I can't open it on OSX. I try to launch it from terminal, but receive this errors log:

`Mac-mini:~ MyMac$ /Applications/FontForge.app/Contents/MacOS/FontForge
PKGBASE: /Applications/FontForge.app
Mac-mini:~ MyMac$ dyld: Library not loaded: /opt/local/lib/libfontforgeexe.2.dylib
  Referenced from: /Applications/FontForge.app/Contents/Resources/opt/local/bin/fontforge
  Reason: image not found
Traceback (most recent call last):
  File "/Applications/FontForge.app/Contents/MacOS/fontforge-crash-reporter.py", line 3, in <module>
    import SimpleHTTPServer
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/SimpleHTTPServer.py", line 15, in <module>
    import BaseHTTPServer
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/BaseHTTPServer.py", line 81, in <module>
    import mimetools
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/mimetools.py", line 6, in <module>
    import tempfile
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/tempfile.py", line 35, in <module>
    from random import Random as _Random
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/random.py", line 48, in <module>
    from binascii import hexlify as _hexlify
ImportError: dlopen(/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/lib-dynload/binascii.so, 2): Library not loaded: /opt/local/lib/libz.1.dylib
  Referenced from: /Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/lib-dynload/binascii.so
  Reason: image not found`

**Comment by eabay** [comment]
No need to have this issue anymore I think.

Closing since there is no response.
